const CONSTANTS = {};
CONSTANTS.ENDPOINT = {};

CONSTANTS.PORT = process.env.PORT || "3001";
CONSTANTS.ENDPOINT.LIST = "/list";

CONSTANTS.ENDPOINT.GRID = "/grid";

CONSTANTS.ENDPOINT.MASTERDETAIL = "/masterdetail";

CONSTANTS.ENDPOINT.GLOBAL = "/global";

CONSTANTS.ENDPOINT.COUNTRY = "/country";

module.exports = CONSTANTS;
